#This only works on macos
# basicVisuals:
# 	clang++ -std=c++14 basicVisuals.cpp boids.cpp -DGL_SILENCE_DEPRECATION \
# 		-framework OpenGL -framework GLUT \
# 		-o drones

#this works on linux
basicVisuals:
	clang++ -std=c++14 basicVisuals.cpp boids.cpp \
		-lGL -lGLU -lglut \
		-o drones

